def x():
    """
    The doumentation for a function is generated by the string right
    after the functions definition.
    """
    pass


def x1():

    """
    Whitespace doesnt matter
    """
    pass


def x2():

    "As a matter of fact, it doesnt even need to be triple quoted"
    pass


def x3():
    pass

    """
    But it does have to be the first line
    """
    pass


def x4():
    """And it can't be an expression""".replace("can't", "CANNOT")
    pass

print x.__doc__
print x1.__doc__
print x2.__doc__
print x3.__doc__
print x4.__doc__
